### ISSUE TITLE
How to use nativeTask, provide example please.

### ISSUE THREAD

**Issue by reecefowell** [betsol/gulp-require-tasks#4]
Please provide an example of how to use nativeTask.

Thanks

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

Natives tasks works practically the same as with `fn` function. The difference is that `nativeTask` gets executed directly by Gulp and we're not passing anything to it additionally.

I'm not sure we should add specific example for it, cause it's probably a pretty straightforward concept.

If you have any further questions, please let me know. Cheers!

**Comment by 7studio** [comment]
Hi Slava,
Sorry to comment on a closed issue but I have the same question as Reece. I don't understand the use of `nativeTask`.
First of all, I thought `nativeTask` could be used like this : `gulp mytask` according to your sentence 

> Also, you could use nativeTask instead of fn property to make your task function executed by Gulp directly. 

But it does not :/ Maybe I didn't understand your words or I missed something.

Here is my env.:
* gulp 3.9.1
* gulp-require-tasks  1.0.5

```
// gulpfile.babel.js

import gulp from 'gulp';
import tasks from 'gulp-require-tasks';

task({
  path: process.cwd() + '/gulp/tasks',
  gulp: gulp
});
```
```
// gulp/tasks/build/styles.js:

const postcss = require('gulp-postcss');

module.exports =  {
  nativeTask: function() {
    return gulp.src('...')
      .pipe(postcss(processors))
      .pipe(gulp.dest('...'));
  }
};
```

When I try : `gulp build:styles` I get the following error `ReferenceError: gulp is not defined at Gulp.nativeTask` but when I do : 

```
// gulp/tasks/build/styles.js:

const compass = require('compass');

module.exports =  function(gulp, done) {
  return gulp.src('...')
    .pipe(compass())
    .pipe(gulp.dest('...'));
};
```
Everything is ok.

Thank you for your anwser.
Xavier.

**Comment by slavafomin** [comment]
Hello @7studio! Thank you for using this module.

1). You have multiple errors in the code you've specified.
2). Why do you want to use `nativeTask` in the first place? What is your use case?

**Comment by 7studio** [comment]
Thank you for your time and your answer, but:
1. Can you point to me the multiple errors in my code :wink: I would like to understand and learn from my mistakes. 
2. I wanted to use this method because of the misunderstanding of this sentence: "task function executed by Gulp directly". In other way, all my code (it's not the same as in the comment) works like a charm but I didn't understand how your plugin works :relieved: and especially the difference between `fn` and `nativeTask`.
If I mix the Gulp [code](https://github.com/gulpjs/gulp/blob/master/docs/API.md#fn) and your [code](https://github.com/betsol/gulp-require-tasks/blob/master/index.js#L44) I am even more confused today. 

Can you provide some examples of the uses of `nativeTask` please ?

**Comment by slavafomin** [comment]
@7studio please see this: https://github.com/betsol/gulp-require-tasks#synchronous-tasks and this: https://github.com/betsol/gulp-require-tasks/issues/9.

The `nativeTask` is a workaround for problems with synchronous tasks. Normally this module wraps the gulp task with it's own function, but using the `nativeTask` you can have a function which will be executed **directly** without wrapper. So this functionality is here for rare edge cases. I would recommend to always return stream or promise from your gulp function.

Considering mistakes in code I would recommend to use some decent IDE, like [WebStorm](https://www.jetbrains.com/webstorm/) it will highlight errors for you automatically. Cheers!
